version: '2'

services:
  phpunit:
    build: '.'
    entrypoint: 'tail -f /dev/null'
    volumes:
      - ./:/how-to-use-phpunit
    links:
      - "hub"

  chrome:
    image: selenium/node-chrome:3.8.1-erbium
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub

  hub:
    image: selenium/hub:3.8.1-erbium
    ports:
      - "4444:4444"
